from __future__ import annotations


PROTOCOL_VERSION = "0.1"


def agent_info_payload() -> dict:
    return {
        "name": "transvortex",
        "protocol_version": PROTOCOL_VERSION,
        "machine_readable": True,
        "recommended_workflow": [
            "transvortex agent-info --json",
            "transvortex doctor --json",
            "transvortex probe-provider --strict",
            "transvortex run --input <video> --src <lang> --tgt <lang> --detach --json",
            "transvortex events --task-id <task_id> --follow",
            "transvortex status --task-id <task_id> --json",
            "transvortex result open --task-id <task_id> --json",
        ],
        "commands": {
            "run": {"long_running": True, "supports_json": True, "supports_stream_events": True, "supports_detach": True},
            "resume": {"long_running": True, "supports_json": True, "supports_stream_events": True, "supports_detach": True},
            "asr": {"long_running": True, "supports_json": True, "supports_detach": True},
            "translate": {"long_running": True, "supports_json": True, "supports_detach": True},
            "export": {"long_running": False, "supports_json": True},
            "status": {"supports_json": True},
            "events": {"outputs": "jsonl", "supports_follow": True},
            "cancel": {"supports_json": True},
            "tasks": {"supports_json": True},
            "doctor": {"supports_json": True},
            "probe-provider": {"supports_json": True, "strict_exit_code": True},
            "config show": {"supports_json": True},
            "result open": {"supports_json": True},
            "reexport": {"supports_json": True},
        },
        "statuses": [
            "INIT",
            "QUEUED",
            "PRECHECK",
            "INGEST",
            "ASR",
            "SEGMENT",
            "TRANSLATE",
            "ALIGN",
            "EXPORT",
            "DONE",
            "FAILED",
            "CANCEL_REQUESTED",
            "CANCELLED",
        ],
        "event_schema": {
            "format": "jsonl",
            "required_fields": ["type", "task_id", "created_at", "level", "message"],
            "optional_fields": ["stage", "progress", "details"],
            "terminal_types": ["done", "error", "cancelled"],
            "known_types": [
                "task_created",
                "resume_requested",
                "stage",
                "progress",
                "artifact",
                "warning",
                "error",
                "done",
                "cancel_requested",
                "cancelled",
                "edited",
                "reexported",
            ],
        },
        "artifact_contract": [
            "task.json",
            "checkpoint.json",
            "events.jsonl",
            "media/",
            "asr/segments.raw.jsonl",
            "chunks/chunks.json",
            "translate/segments.translated.jsonl",
            "translate/validation.jsonl",
            "translate/repairs.jsonl",
            "final/segments.final.json",
            "output/*.srt",
            "output/*.ass",
        ],
        "error_info_schema": {
            "fields": ["code", "type", "stage", "message", "hint_zh", "retryable", "details"],
            "known_codes": [
                "input_not_found",
                "missing_env",
                "missing_executable",
                "missing_asr_dependency",
                "provider_preflight_failed",
                "provider_not_found",
                "artifact_missing",
                "no_segments",
                "translation_failed",
                "task_cancelled",
                "runtime_error",
            ],
        },
        "rules": [
            "Do not parse human-formatted output.",
            "Use --json for single-response commands.",
            "Use --stream-events or events --follow for long-running task progress.",
            "Read artifacts only from task_dir returned by JSON status or detach response.",
            "Never expect secret values in config or agent-info output.",
        ],
    }
