from __future__ import annotations

from pathlib import Path

from ..app.agent_entry import AGENT_PROTOCOL_VERSION, runtime_agent_context
from .agent_setup import SETUP_SCOPES


PROTOCOL_VERSION = AGENT_PROTOCOL_VERSION


def agent_info_payload(*, root_dir: Path | None = None) -> dict:
    root = (root_dir or Path.cwd()).expanduser().resolve()
    installation = runtime_agent_context(root_dir=root)
    cli_prefix = list(installation["cli_argv_prefix"])

    def cli_argv(*parts: str) -> list[str]:
        return [*cli_prefix, *parts]

    return {
        "name": "transvortex",
        "protocol_version": PROTOCOL_VERSION,
        "machine_readable": True,
        "installation": installation,
        "setup_contract": {
            "contract": "transvortex.agent_setup",
            "schema_version": 2,
            "kinds": [
                "setup_plan",
                "setup_verify",
                "managed_apply",
                "model_probe",
                "model_register",
                "accelerator_probe",
                "accelerator_register",
                "resources_activate",
                "provider_test",
                "agent_plan",
                "agent_result",
            ],
            "read_only_commands": [
                "transvortex asr setup-plan --scope <scope> --json",
                "transvortex asr setup-verify --scope <scope> --json [--strict for full]",
            ],
            "read_only_argv": [
                cli_argv("asr", "setup-plan", "--scope", "full", "--json"),
                cli_argv("asr", "setup-verify", "--scope", "full", "--json", "--strict"),
            ],
            "root_argument": "--root <config-root>",
            "providers_file_argument": "--providers-file <providers-file>",
            "scope_argument": "--scope <inspect|prepare_model|prepare_accelerator|register|full>",
            "supported_scopes": list(SETUP_SCOPES),
            "strict_scope": "full",
            "schema_asset": "agent/references/setup_contract.schema.json",
            "workflow_asset": "agent/workflows/ASR_ENVIRONMENT_SETUP.md",
            "packaged_schema_asset": "agent/references/setup_contract.schema.json",
            "packaged_workflow_asset": "agent/workflows/ASR_ENVIRONMENT_SETUP.md",
        },
        "recommended_argv": [
            cli_argv("agent-info", "--json"),
            cli_argv("asr", "setup-plan", "--scope", "full", "--json"),
            cli_argv("asr", "setup-verify", "--scope", "full", "--json", "--strict"),
        ],
        "recommended_workflow": [
            "transvortex agent-info --json",
            "transvortex asr setup-plan --scope <scope> --json",
            "inspect the local environment and execute only the user-selected preparation scope",
            "treat current_configuration as an inspection baseline and let the Agent select model, device, and resource sources",
            "use advertised setup-apply for managed resources, or prepare external resources with Agent tools",
            "register and activate external resources with the advertised TransVortex commands",
            "if provider_mode is local_service or remote_provider: run the advertised asr engine-test command",
            "for an already deployed FunASR service: save only a verified launch recipe with the advertised funasr-launcher-save command; do not install or repair FunASR unless the user separately requests it",
            "for full: transvortex asr setup-verify --scope full --json --strict",
            "for other scopes: transvortex asr setup-verify --scope <scope> --json and read scope_result separately from asr_ready",
            "transvortex probe-provider --strict",
            "transvortex run --input <video> --src <lang> --tgt <lang> --detach --json",
            "transvortex events --task-id <task_id> --follow",
            "transvortex status --task-id <task_id> --json",
            "transvortex result open --task-id <task_id> --json",
            "transvortex memory collections --json",
            "transvortex memory collection-get --collection-id <collection_id> --json",
            "transvortex memory resolve --collection-id <collection_id> --src <lang> --tgt <lang> --json",
            "transvortex memory promote --task-id <task_id> --collection-id <collection_id> --entry-id <entry_id> --expected-revision <revision> --dry-run --json",
            "transvortex memory bootstrap --segments <segments.jsonl> --src <lang> --tgt <lang> --preset-id <preset_id> --json",
            "transvortex memory export-preset --task-id <task_id> --preset-id <preset_id> --json",
        ],
        "commands": {
            "run": {
                "long_running": True,
                "supports_json": True,
                "supports_stream_events": True,
                "supports_detach": True,
                "supports_request_json": True,
                "immediate_task_id": "use --detach --json",
                "detach_response": "queued receipt only; terminal=false; follow events or status for final result",
                "json_timing": "without --detach, JSON is printed only after the task reaches a terminal state",
            },
            "resume": {
                "long_running": True,
                "supports_json": True,
                "supports_stream_events": True,
                "supports_detach": True,
                "supports_request_json": True,
                "immediate_task_id": "use --detach --json",
                "detach_response": "queued receipt only; terminal=false; follow events or status for final result",
                "json_timing": "without --detach, JSON is printed only after the task reaches a terminal state",
            },
            "asr": {
                "long_running": True,
                "supports_json": True,
                "supports_detach": True,
                "immediate_task_id": "use --detach --json",
                "detach_response": "queued receipt only; terminal=false; follow events or status for final result",
                "json_timing": "without --detach, JSON is printed only after the task reaches a terminal state",
            },
            "asr setup-plan": {
                "long_running": False,
                "supports_json": True,
                "read_only": True,
                "network_access": False,
                "purpose": "Describe provider mode, independently sourced resources, current state, and executable setup actions",
                "supported_scopes": list(SETUP_SCOPES),
                "command": "transvortex --root <config-root> asr setup-plan --scope <scope> --providers-file <providers-file> --json",
            },
            "asr setup-apply": {
                "long_running": True,
                "supports_json": True,
                "read_only": False,
                "network_access": True,
                "executor": "transvortex",
                "ownership": "transvortex",
                "resources": ["setup", "runtime", "model", "accelerator"],
                "purpose": "Apply a catalog-backed resource managed by TransVortex",
                "command": "transvortex --root <config-root> asr setup-apply --resource <resource> --item-id <item-id> --providers-file <providers-file> --json",
            },
            "asr model-probe": {
                "long_running": False,
                "supports_json": True,
                "read_only": True,
                "network_access": False,
                "ownership": "external",
                "command": "transvortex --root <config-root> asr model-probe --model-path <model-path> --providers-file <providers-file> --json",
            },
            "asr model-register": {
                "long_running": False,
                "supports_json": True,
                "read_only": False,
                "network_access": False,
                "ownership": "external",
                "writes": ["resource registration"],
                "command": "transvortex --root <config-root> asr model-register --model-path <model-path> [--label <display-name>] --providers-file <providers-file> --json",
            },
            "asr accelerator-probe": {
                "long_running": False,
                "supports_json": True,
                "read_only": True,
                "network_access": False,
                "ownership": "external",
                "command": "transvortex --root <config-root> asr accelerator-probe --accelerator-root <accelerator-root> --providers-file <providers-file> --json",
            },
            "asr accelerator-register": {
                "long_running": False,
                "supports_json": True,
                "read_only": False,
                "network_access": False,
                "ownership": "external",
                "writes": ["resource registration"],
                "command": "transvortex --root <config-root> asr accelerator-register --accelerator-root <accelerator-root> --providers-file <providers-file> --json",
            },
            "asr resources-activate": {
                "long_running": False,
                "supports_json": True,
                "read_only": False,
                "network_access": False,
                "writes": ["active ASR resource references"],
                "purpose": "Attach managed IDs or verified external registrations to the active local worker",
                "command": "transvortex --root <config-root> asr resources-activate <resource-selection> [--device <device>] [--compute-type <compute-type>] --providers-file <providers-file> --json",
            },
            "asr setup-verify": {
                "long_running": False,
                "supports_json": True,
                "read_only": True,
                "network_access": False,
                "supports_strict": True,
                "strict_scope": "full",
                "supported_scopes": list(SETUP_SCOPES),
                "purpose": "Report scope completion separately from full ASR readiness without network access",
                "command": "transvortex --root <config-root> asr setup-verify --scope <scope> [--strict for full] --providers-file <providers-file> --json",
            },
            "asr engine-test": {
                "long_running": False,
                "supports_json": True,
                "read_only": False,
                "network_access": True,
                "requires_user_authorization": True,
                "writes_only_probe_status": True,
                "may_upload_media": True,
                "command_local_service": "transvortex --root <config-root> asr engine-test --confirm-network --providers-file <providers-file> --json",
                "command_remote": "transvortex --root <config-root> asr engine-test --confirm-network --confirm-media --confirm-cost --providers-file <providers-file> --json",
            },
            "asr funasr-launcher-status": {
                "long_running": False,
                "supports_json": True,
                "read_only": True,
                "network_access": "loopback health check only",
                "ownership": "external",
                "command": "transvortex --root <config-root> asr funasr-launcher-status --json",
            },
            "asr funasr-launcher-save": {
                "long_running": False,
                "supports_json": True,
                "read_only": False,
                "network_access": "loopback health check only",
                "ownership": "external",
                "writes": ["external FunASR launch recipe"],
                "purpose": "Persist executable, argv, working directory, and loopback health URL after the Agent has verified the deployment",
                "command": "transvortex --root <config-root> asr funasr-launcher-save --json-payload <launcher-json> --json",
            },
            "asr funasr-launcher-remove": {
                "long_running": False,
                "supports_json": True,
                "read_only": False,
                "destructive": True,
                "requires_confirmation_flag": "--yes",
                "writes": ["external FunASR launch recipe"],
                "does_not_modify": ["FunASR environment", "models", "running external service"],
                "command": "transvortex --root <config-root> asr funasr-launcher-remove --yes --json",
            },
            "translate": {
                "long_running": True,
                "supports_json": True,
                "supports_detach": True,
                "immediate_task_id": "use --detach --json",
                "detach_response": "queued receipt only; terminal=false; follow events or status for final result",
                "json_timing": "without --detach, JSON is printed only after the task reaches a terminal state",
            },
            "export": {"long_running": False, "supports_json": True},
            "status": {"supports_json": True},
            "events": {"outputs": "jsonl", "supports_follow": True},
            "cancel": {"supports_json": True},
            "tasks": {"supports_json": True},
            "doctor": {"supports_json": True},
            "probe-provider": {
                "supports_json": True,
                "strict_exit_code": True,
                "network_access": False,
                "requires_user_authorization": False,
                "purpose": "Validate translation provider URL/payload/response mapping without sending a request",
            },
            "config show": {"supports_json": True},
            "result open": {"supports_json": True},
            "memory collections": {"supports_json": True, "read_only": True},
            "memory collection-get": {"supports_json": True, "read_only": True},
            "memory collection-create": {
                "supports_json": True,
                "read_only": False,
                "writes": ["persistent memory collection"],
            },
            "memory collection-update": {
                "supports_json": True,
                "supports_dry_run": True,
                "requires_expected_revision": True,
                "writes": ["persistent memory collection metadata"],
            },
            "memory collection-delete": {
                "supports_json": True,
                "destructive": True,
                "requires_confirmation_flag": "--yes",
                "requires_expected_revision": True,
            },
            "memory entry-upsert": {
                "supports_json": True,
                "supports_dry_run": True,
                "requires_expected_revision": True,
                "writes": ["persistent memory collection entry"],
            },
            "memory entry-delete": {
                "supports_json": True,
                "supports_dry_run": True,
                "destructive": True,
                "requires_confirmation_flag": "--yes unless --dry-run",
                "requires_expected_revision": True,
            },
            "memory promote": {
                "supports_json": True,
                "supports_dry_run": True,
                "requires_expected_revision": True,
                "selection_required": "repeat --entry-id; task candidates are never persisted implicitly",
                "conflict_policies": ["skip", "replace"],
            },
            "memory resolve": {
                "supports_json": True,
                "read_only": True,
                "purpose": "Preview the immutable collection snapshot a task would receive",
            },
            "memory bootstrap": {"supports_json": True, "supports_dry_run": True},
            "memory export-preset": {"supports_json": True, "supports_dry_run": True},
            "reexport": {"supports_json": True, "supports_bilingual_override": True},
        },
        "statuses": [
            "INIT",
            "QUEUED",
            "PRECHECK",
            "INGEST",
            "ASR",
            "MEMORY",
            "SEGMENT",
            "TRANSLATE",
            "ALIGN",
            "QUALITY",
            "EXPORT",
            "DONE",
            "FAILED",
            "INTERRUPTED",
            "CANCEL_REQUESTED",
            "CANCELLED",
        ],
        "event_schema": {
            "format": "jsonl",
            "required_fields": ["type", "task_id", "created_at", "level", "message"],
            "optional_fields": ["stage", "progress", "details"],
            "terminal_types": ["done", "error", "cancelled", "interrupted"],
            "known_types": [
                "task_created",
                "resume_requested",
                "stage",
                "progress",
                "artifact",
                "warning",
                "error",
                "done",
                "cancel_requested",
                "cancelled",
                "interrupted",
                "edited",
                "reexported",
            ],
        },
        "artifact_contract": [
            "task.json",
            "checkpoint.json",
            "events.jsonl",
            "source/segments.raw.jsonl",
            "source/segments.normalized.jsonl",
            "source/embedded_subtitle.srt",
            "source/subtitle_streams.json",
            "source/asr/raw/*.json",
            "source/asr/rows/*.json",
            "source/asr/preprocess/*.json",
            "chunks/chunks.json",
            "translate/segments.translated.jsonl",
            "translate/validation.jsonl",
            "translate/repairs.jsonl",
            "memory/selected_presets.json",
            "memory/selected_collections.json",
            "memory/translation_memory.json",
            "memory/memory_patches.jsonl",
            "memory/rejected_memory_candidates.jsonl",
            "memory/conflicts.jsonl",
            "memory/consistency_issues.jsonl",
            "memory/snapshots/*.json",
            "quality/compression.jsonl",
            "quality/reflow.jsonl",
            "quality/source_cleaning.json",
            "quality/asr_boundary_quality.json",
            "quality/asr_word_overlap.json",
            "quality/subtitle_quality.json",
            "quality/subtitle_delivery.json",
            "final/segments.aligned.json",
            "final/segments.reflowed.json",
            "final/segments.final.json",
            "output/*.srt",
            "output/*.ass",
            "output/*.vtt",
            "output/*.lrc",
        ],
        "error_info_schema": {
            "fields": ["code", "type", "stage", "message", "hint_zh", "retryable", "details"],
            "known_codes": [
                "input_not_found",
                "missing_env",
                "missing_executable",
                "missing_asr_dependency",
                "provider_preflight_failed",
                "provider_not_found",
                "artifact_missing",
                "no_segments",
                "translation_failed",
                "task_cancelled",
                "runtime_error",
            ],
        },
        "rules": [
            "Do not parse human-formatted output.",
            "Use --json for single-response commands.",
            "For long-running commands, --json without --detach returns only after terminal status; use --detach --json to get task_id immediately.",
            "A detached JSON response is a queued receipt, not a terminal task result; treat terminal=false as a requirement to follow events or poll status.",
            "Use --stream-events or events --follow for long-running task progress.",
            "Read artifacts only from task_dir returned by JSON status or detach response.",
            "Never expect secret values in config or agent-info output.",
            "Use result open quality fields and quality/subtitle_quality.json for subtitle readability issues.",
        ],
    }
